from setuptools import setup, find_packages

setup(
    name="sql_rag",
    version="0.1.0",
    description="SQL-based Retrieval Augmented Generation System",
    author="",
    author_email="",
    packages=find_packages(),
    install_requires=[
        "pandas>=1.3.0",
        "pyodbc>=4.0.30",
        "sentence-transformers>=2.2.0",
        "qdrant-client>=1.1.0",
        "streamlit>=1.15.0",
        "python-dotenv>=0.19.0",
        "tqdm>=4.62.0",
        "requests>=2.26.0",
        "numpy>=1.21.0",
        "scikit-learn>=1.0.0",
        "configparser>=5.0.0",
        "ansi2html>=1.5.0",
        "ollama>=0.1.0",
        "langchain>=0.0.267",
        "langchain-community>=0.0.10",
        "pydantic>=1.8.2",
        "typing-extensions>=4.0.0",
        "pytest>=7.0.0",
        "torch>=2.0.0",
        "openai>=1.0.0",
        "plotly>=5.13.0",
        "rich>=12.0.0",
        "inquirer>=3.1.3",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)

